"""
City Name Service for Hotel Agent
Maps IATA codes to human-readable city names
"""

from typing import Dict, Optional

# Common IATA to city name mappings
CITY_NAME_MAPPINGS = {
    "NYC": "New York",
    "LGA": "New York (LaGuardia)",
    "JFK": "New York (JFK)",
    "EWR": "Newark",
    "LON": "London",
    "LHR": "London (Heathrow)",
    "LGW": "London (Gatwick)",
    "PAR": "Paris",
    "CDG": "Paris (Charles de Gaulle)",
    "ORY": "Paris (Orly)",
    "TOK": "Tokyo",
    "NRT": "Tokyo (Narita)",
    "HND": "Tokyo (Haneda)",
    "SYD": "Sydney",
    "MEL": "Melbourne",
    "LAX": "Los Angeles",
    "SFO": "San Francisco",
    "CHI": "Chicago",
    "MIA": "Miami",
    "BOS": "Boston",
    "SEA": "Seattle",
    "DEN": "Denver",
    "LAS": "Las Vegas",
    "PHX": "Phoenix",
    "ATL": "Atlanta",
    "DFW": "Dallas",
    "IAH": "Houston",
    "ORD": "Chicago (O'Hare)",
    "MDW": "Chicago (Midway)",
    "DCA": "Washington D.C.",
    "IAD": "Washington D.C. (Dulles)",
    "BWI": "Baltimore",
    "PHL": "Philadelphia",
    "DTW": "Detroit",
    "MSP": "Minneapolis",
    "SLC": "Salt Lake City",
    "PDX": "Portland",
    "SAN": "San Diego",
    "OAK": "Oakland",
    "SJC": "San Jose",
    "AUS": "Austin",
    "MSY": "New Orleans",
    "MCO": "Orlando",
    "TPA": "Tampa",
    "FLL": "Fort Lauderdale",
    "PBI": "West Palm Beach",
    "JAX": "Jacksonville",
    "CLT": "Charlotte",
    "RDU": "Raleigh",
    "BNA": "Nashville",
    "MEM": "Memphis",
    "STL": "St. Louis",
    "KCI": "Kansas City",
    "OMA": "Omaha",
    "MCI": "Kansas City",
    "DSM": "Des Moines",
    "IND": "Indianapolis",
    "CVG": "Cincinnati",
    "CMH": "Columbus",
    "CLE": "Cleveland",
    "PIT": "Pittsburgh",
    "ROC": "Rochester",
    "BUF": "Buffalo",
    "ALB": "Albany",
    "BDL": "Hartford",
    "PVD": "Providence",
    "BGR": "Bangor",
    "BOS": "Boston",
    "MHT": "Manchester",
    "BTV": "Burlington",
    "POR": "Portland (Maine)",
    "MSP": "Minneapolis",
    "MKE": "Milwaukee",
    "GRR": "Grand Rapids",
    "TOL": "Toledo",
    "DAY": "Dayton",
    "LEX": "Lexington",
    "SDF": "Louisville",
    "EVV": "Evansville",
    "BLV": "Belleville",
    "MDW": "Chicago (Midway)",
    "ORD": "Chicago (O'Hare)",
    "RFD": "Rockford",
    "MLI": "Moline",
    "PIA": "Peoria",
    "SPI": "Springfield (IL)",
    "BMI": "Bloomington",
    "CMI": "Champaign",
    "DEC": "Decatur",
    "MWA": "Marion",
    "QUI": "Quincy",
    "CPS": "St. Louis (Spirit)",
    "STL": "St. Louis",
    "SGF": "Springfield (MO)",
    "COU": "Columbia",
    "MCI": "Kansas City",
    "MKC": "Kansas City (Downtown)",
    "STJ": "St. Joseph",
    "JLN": "Joplin",
    "TBN": "Fort Leonard Wood",
    "IRK": "Kirksville",
    "COU": "Columbia",
    "JEF": "Jefferson City",
    "CGI": "Cape Girardeau",
    "RDU": "Raleigh",
    "CLT": "Charlotte",
    "GSO": "Greensboro",
    "AVL": "Asheville",
    "ILM": "Wilmington",
    "FAY": "Fayetteville",
    "OAJ": "Jacksonville (NC)",
    "EWN": "New Bern",
    "PGV": "Greenville",
    "HKY": "Hickory",
    "INT": "Winston-Salem",
    "RWI": "Rocky Mount",
    "ISO": "Kinston",
    "OCW": "Washington",
    "CPK": "Chesapeake",
    "ORF": "Norfolk",
    "RIC": "Richmond",
    "PHF": "Newport News",
    "CHO": "Charlottesville",
    "LYH": "Lynchburg",
    "ROA": "Roanoke",
    "BLF": "Bluefield",
    "LWB": "Lewisburg",
    "BKW": "Beckley",
    "CRW": "Charleston (WV)",
    "HTS": "Huntington",
    "PKB": "Parkersburg",
    "MGW": "Morgantown",
    "CKB": "Clarksburg",
    "LBE": "Latrobe",
    "DUJ": "DuBois",
    "JST": "Johnstown",
    "AOO": "Altoona",
    "ERI": "Erie",
    "MDT": "Harrisburg",
    "LNS": "Lancaster",
    "IPT": "Williamsport",
    "AVP": "Scranton",
    "AOO": "Altoona",
    "DUJ": "DuBois",
    "LBE": "Latrobe",
    "JST": "Johnstown",
    "ERI": "Erie",
    "MDT": "Harrisburg",
    "LNS": "Lancaster",
    "IPT": "Williamsport",
    "AVP": "Scranton",
    "ABE": "Allentown",
    "RDG": "Reading",
    "ERI": "Erie",
    "AOO": "Altoona",
    "DUJ": "DuBois",
    "LBE": "Latrobe",
    "JST": "Johnstown",
    "MDT": "Harrisburg",
    "LNS": "Lancaster",
    "IPT": "Williamsport",
    "AVP": "Scranton",
    "ABE": "Allentown",
    "RDG": "Reading"
}

def get_city_display_name(iata_code: str) -> str:
    """
    Convert IATA code to human-readable city name
    
    Args:
        iata_code: 3-letter IATA code
        
    Returns:
        Human-readable city name or original code if not found
    """
    return CITY_NAME_MAPPINGS.get(iata_code.upper(), iata_code.upper())

def get_city_info(iata_code: str) -> Dict[str, str]:
    """
    Get detailed city information
    
    Args:
        iata_code: 3-letter IATA code
        
    Returns:
        Dictionary with city information
    """
    display_name = get_city_display_name(iata_code)
    
    return {
        "iata_code": iata_code.upper(),
        "display_name": display_name,
        "is_airport": "(" in display_name,
        "city_name": display_name.split(" (")[0] if "(" in display_name else display_name
    }
